Este colab fue desarrollado por Arnold Charry Armero.

# Numpy en Python

## Ejercicio 1

Crea un array unidimensional de 9 elementos y transfórmalo en un array 3D. Muestra la dimensión y la
shape antes y después del reshape.

In [ ]:
import numpy as np

In [ ]:
a = np.array((1, 2, 3, 4, 5, 6, 7, 8, 9))
print("a =", a)
print("Dimensión:", a.ndim)
print("Shape:", a.shape)
b = a.reshape(1, 3, 3)
print("b =", b)
print("Dimensión:", b.ndim)
print("Shape:", b.shape)

a = [1 2 3 4 5 6 7 8 9]
Dimensión: 1
Shape: (9,)
b = [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimensión: 3
Shape: (1, 3, 3)


## Ejercicio 2

Dados los arrays 2D [[-6, -5], [-4, -3], [-2, -1]] y [[1, 2], [3, 4], [5, 6]], concaténalos de
modo que obtengas el array [[1, 2, -6, -5], [3, 4, -4, -3] [5, 6, -2, -1]].

In [ ]:
# Concatenamos arrays 2D
b1 = np.array([[-6, -5], [-4, -3], [-2, -1]])
b2 = np.array([[1, 2], [3, 4], [5, 6]])

# Con axis = 1
b = np.concatenate((b2, b1), axis = 1)
print("\naxis = 1 nos devuelve\n", b)


axis = 1 nos devuelve
 [[ 1  2 -6 -5]
 [ 3  4 -4 -3]
 [ 5  6 -2 -1]]


## Ejercicio 3

Dado el array 2D [[1, 2, 3], [-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]], divídelo en 3 arrays 2D.

In [ ]:
a = np.array([[1, 2, 3], [-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]])
b1, b2, b3 = np.split(a, 3)
print("b1 =", b1)
print("Dimensión:", b1.ndim)
print("b2 =", b2)
print("Dimensión:", b2.ndim)
print("b3 =", b3)
print("Dimensión:", b3.ndim)

b1 = [[ 1  2  3]
 [-1  0  1]]
Dimensión: 2
b2 = [[ 4  5  6]
 [-4  0  4]]
Dimensión: 2
b3 = [[ 3  2  1]
 [-3  0  3]]
Dimensión: 2


## Ejercicio 4

Dado el array 2D [["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato",
"elle"]], busca las palabras que sean palíndromos.
PISTA: Necesitarás una función universal.

In [ ]:
a = np.array([["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato", "elle"]])

def IsPalindrome(s):
  s = s.lower()
  word1 = ""
  word2 = ""
  for i in s:
    word1 += i
  for i in s[::-1]:
    word2 += i
  if word1 == word2:
      return True
  return False

my_palindrome = np.frompyfunc(IsPalindrome, 1, 1)
print(my_palindrome(a))

[[True False False]
 [False True False]
 [False False True]]


## Ejercicio 5

Dado el array 1D ["cena", "frío", "kayak", "remo", "sol"]], ¿qué índice deberá ocupar el elemento
“python” para que se mantenga el orden alfabético?


In [ ]:
a = np.array(["cena", "frío",  "kayak", "remo", "sol"])
b = np.searchsorted(a, "python", side = "right")
print("El elemento python deberá ocupar el índice", b)

El elemento python deberá ocupar el índice 3


## Ejercicio 6

Crea un minijuego que piense un número aleatorio entre 1 y 10 y, hasta que no lo aciertes, te pida un número
del 1 al 10. Cuando aciertes, tendrá que devolver el número de intentos y la frase: “¡¡¡ENHORABUENA!!!
Has acertado el número que había pensado: el {}”. En caso de que falles, el juego deberá mostrar la frase
“¡Has fallado! ¡Prueba otra vez!”


In [ ]:
from numpy import random

value = random.randint(1, 11)
number = int(input("Piense un número entre 1 y 10: "))
cont = 1
while value != number:
  value = random.randint(1, 11)
  number = int(input("Piense un número entre 1 y 10: "))
  cont += 1
  print("Has fallado! ¡Prueba otra vez!")
else:
  print("¡¡¡ENHORABUENA!!! Has acertado el número que había pensado:", number)
  print(f"Las veces que has intentado fueron de {cont}")

Piense un número entre 1 y 10: 4
Piense un número entre 1 y 10: 6
Has fallado! ¡Prueba otra vez!
Piense un número entre 1 y 10: 5
Has fallado! ¡Prueba otra vez!
Piense un número entre 1 y 10: 2
Has fallado! ¡Prueba otra vez!
Piense un número entre 1 y 10: 8
Has fallado! ¡Prueba otra vez!
Piense un número entre 1 y 10: 1
Has fallado! ¡Prueba otra vez!
Piense un número entre 1 y 10: 3
Has fallado! ¡Prueba otra vez!
Piense un número entre 1 y 10: 7
Has fallado! ¡Prueba otra vez!
Piense un número entre 1 y 10: 8
Has fallado! ¡Prueba otra vez!
Piense un número entre 1 y 10: 6
Has fallado! ¡Prueba otra vez!
Piense un número entre 1 y 10: 5
Has fallado! ¡Prueba otra vez!
Piense un número entre 1 y 10: 4
Has fallado! ¡Prueba otra vez!
Piense un número entre 1 y 10: 3
Has fallado! ¡Prueba otra vez!
Piense un número entre 1 y 10: 2
Has fallado! ¡Prueba otra vez!
Piense un número entre 1 y 10: 1
Has fallado! ¡Prueba otra vez!
Piense un número entre 1 y 10: 5
Has fallado! ¡Prueba otra vez!
Piense 

## Ejercicio 7

Crea un minijuego que piense un array 1D aleatorio de 5 elementos. Los elementos serán números enteros
entre 1 y 20. Para cada intento, primero tendrá que pedir 5 números enteros del 1 al 20. El juego nos tendrá
que decir cuántos números del array hemos acertado y cuántos números del array están bien colocados. El
juego no termina hasta que no se hayan acertado todos los números pensados en la posición correspondiente.
Al acabar, se tendrá que mostrar la frase: “¡¡¡ENHORABUENA!!! Has acertado el array que había pensado:
{}”


In [ ]:
a = np.array([random.randint(1, 21), random.randint(1, 21), random.randint(1, 21), random.randint(1, 21), random.randint(1, 21)])
b = [0] * len(a)

while not np.array_equal(b, a):
  b = []
  for i in range(5):
    b.append(int(input("Piense un número entre 1 y 20: ")))
  b = np.array(b)

  for i in range(5):
    if b[i] == a[i]:
      print("Has acertado el número", a[i] , "en la posición", i)

  for i in range(5):
    if b[i] in a:
      print("Has acertado el número", b[i])
    else:
      print("No has acertado el número", b[i])
else:
  print("¡¡¡ENHORABUENA!!! Has acertado el array que había pensado:", a)

Piense un número entre 1 y 20: 2
Piense un número entre 1 y 20: 3
Piense un número entre 1 y 20: 4
Piense un número entre 1 y 20: 5
Piense un número entre 1 y 20: 6
No has acertado el número 2
No has acertado el número 3
No has acertado el número 4
No has acertado el número 5
Has acertado el número 6
Piense un número entre 1 y 20: 6
Piense un número entre 1 y 20: 11
Piense un número entre 1 y 20: 12
Piense un número entre 1 y 20: 8
Piense un número entre 1 y 20: 3
Has acertado el número 6 en la posición 0
Has acertado el número 6
No has acertado el número 11
No has acertado el número 12
No has acertado el número 8
No has acertado el número 3
Piense un número entre 1 y 20: 6
Piense un número entre 1 y 20: 10
Piense un número entre 1 y 20: 4
Piense un número entre 1 y 20: 18
Piense un número entre 1 y 20: 24
Has acertado el número 6 en la posición 0
Has acertado el número 6
No has acertado el número 10
No has acertado el número 4
No has acertado el número 18
No has acertado el número 24


## Ejercicio 8

A partir de la lista [-3, -2, -1, 0, 1, 2, 3], genera dos arrays aleatorios 2D de size = (3, 4) y
súmalos.


In [ ]:
import numpy as np

# Lista original de números con un elemento adicional para tener 12 elementos
lista = np.array([-3, -2, -1, 0, 1, 2, 3, 0, 0, 0, 0, 0])

# Generamos dos arreglos 2D aleatorios a partir de la lista original
arreglo1 = np.random.permutation(lista).reshape(3, 4)
arreglo2 = np.random.permutation(lista).reshape(3, 4)

# Sumamos los dos arreglos
resultado = arreglo1 + arreglo2

print("Arreglo 1:\n", arreglo1)
print("Arreglo 2:\n", arreglo2)
print("Suma de Arreglo 1 y Arreglo 2:\n", resultado)

Arreglo 1:
 [[-1  0  0 -2]
 [ 0  3  2  0]
 [ 0  1  0 -3]]
Arreglo 2:
 [[ 0 -2  0  2]
 [ 0  3  0 -1]
 [ 0  1  0 -3]]
Suma de Arreglo 1 y Arreglo 2:
 [[-1 -2  0  0]
 [ 0  6  2 -1]
 [ 0  2  0 -6]]


## Ejercicio 9

Crea una función universal que dado un array de strings devuelva el número total de vocales de cada string.


In [ ]:
import numpy as np

# Función para contar las vocales en una cadena
def count_vowels(s):
    count = 0
    vowels = set("aeiouAEIOU")
    for char in s:
        if char in vowels:
            count += 1
    return count

# Crear una función vectorizada a partir de count_vowels
count_vowels_vec = np.vectorize(count_vowels)

# Pedimos al usuario que ingrese el número de palabras
n = int(input("¿Cuántas palabras quieres introducir?: "))

# Lista para almacenar las palabras
list1 = []
for i in range(n):
    a = input("Introduce una palabra: ")
    list1.append(a)

# Convertimos la lista en un array de numpy
AB = np.array(list1)

# Aplicamos la función vectorizada al array
my_vowels = count_vowels_vec(AB)

# Imprimimos el resultado
print("Número de vocales en cada palabra:", my_vowels)

¿Cuántas palabras quieres introducir?: 1
Introduce una palabra: Arnold
Número de vocales en cada palabra: [2]


## Ejercicio 10

Crea una función universal que dados un array 1D de valores string y conjunto de strings, compruebe para
cada elemento del array 1D, si está presente o no en el conjunto.

In [ ]:
import numpy as np

# Función para comprobar si un string está en el conjunto
def is_in_set(s, string_set):
    return s in string_set

# Crear una función vectorizada a partir de is_in_set
is_in_set_vec = np.vectorize(is_in_set, excluded=['string_set'])

# Definir el conjunto de strings
string_set = {"apple", "banana", "cherry"}

# Pedimos al usuario que ingrese el número de palabras
n = int(input("¿Cuántas palabras quieres introducir?: "))

# Lista para almacenar las palabras
list1 = []
for i in range(n):
    a = input("Introduce una palabra: ")
    list1.append(a)

# Convertimos la lista en un array de numpy
AB = np.array(list1)

# Aplicamos la función vectorizada al array
present_in_set = is_in_set_vec(AB, string_set=string_set)

# Imprimimos el resultado
print("Comprobación de presencia en el conjunto:", present_in_set)

¿Cuántas palabras quieres introducir?: 2
Introduce una palabra: Arnold
Introduce una palabra: apple
Comprobación de presencia en el conjunto: [False  True]
