Este colab fue desarrollado por Arnold Charry Armero

# Utilización de Numpy

In [1]:
# Importar librerias
import numpy as np

In [2]:
temperaturas = np.array([[22, 25, 20], [24, 27, 22], [21, 23, 19], [25, 29, 24], [26, 30, 25], [23, 28, 22],
 [24, 26, 21], [22, 25, 20], [27, 31, 26], [28, 32, 27], [29, 33, 28], [21, 24, 19], [20, 23, 18], [19, 22, 17],
  [23, 26, 21], [24, 28, 23], [25, 29, 24], [26, 30, 25], [27, 31, 26], [28, 32, 27], [29, 33, 28], [30, 34, 29],
   [22, 25, 20], [24, 27, 22], [21, 24, 19], [20, 23, 18], [19, 22, 17], [23, 26, 21], [24, 28, 23], [25, 29, 24]])

In [5]:
print("Temperaturas Promedio")
print(f"Temperatura ciudad 1: {round(float(np.mean(temperaturas[:][0])), 2)}")
print(f"Temperatura ciudad 1: {round(float(np.mean(temperaturas[:][1])), 2)}")
print(f"Temperatura ciudad 1: {round(float(np.mean(temperaturas[:][2])), 2)}")

Temperaturas Promedio
Temperatura ciudad 1: 22.33
Temperatura ciudad 1: 24.33
Temperatura ciudad 1: 21.0


In [6]:
print("Temperaturas Mínima")
print(f"Temperatura ciudad 1: {round(float(min(temperaturas[:][0])), 2)}")
print(f"Temperatura ciudad 1: {round(float(min(temperaturas[:][1])), 2)}")
print(f"Temperatura ciudad 1: {round(float(min(temperaturas[:][2])), 2)}")

Temperaturas Mínima
Temperatura ciudad 1: 20.0
Temperatura ciudad 1: 22.0
Temperatura ciudad 1: 19.0


In [7]:
print("Temperaturas Máximas")
print(f"Temperatura ciudad 1: {round(float(max(temperaturas[:][0])), 2)}")
print(f"Temperatura ciudad 1: {round(float(max(temperaturas[:][1])), 2)}")
print(f"Temperatura ciudad 1: {round(float(max(temperaturas[:][2])), 2)}")

Temperaturas Máximas
Temperatura ciudad 1: 25.0
Temperatura ciudad 1: 27.0
Temperatura ciudad 1: 23.0


In [17]:
dias_calientes = np.any(temperaturas > 30, axis=1)
print(f"Días con temperaturas mayores a 30 grados: {np.where(dias_calientes)[0] + 1}")
dias_frios = np.all(temperaturas < 20, axis=1)
print(f"Días con temperaturas menores a 20 grados: {np.where(dias_frios)[0] + 1}")

Días con temperaturas mayores a 30 grados: [ 9 10 11 19 20 21 22]
Días con temperaturas menores a 20 grados: []


In [18]:
temperaturas_f = (temperaturas * 9/5) + 32
print("Temperaturas en °F (primeros 5 días):\n", temperaturas_f[:5])

Temperaturas en °F (primeros 5 días):
 [[71.6 77.  68. ]
 [75.2 80.6 71.6]
 [69.8 73.4 66.2]
 [77.  84.2 75.2]
 [78.8 86.  77. ]]


In [19]:
temp_min = np.min(temperaturas)
temp_max = np.max(temperaturas)

temperaturas_norm = (temperaturas - temp_min) / (temp_max - temp_min)
print("Temperaturas normalizadas (0-1):\n", temperaturas_norm[:5])

Temperaturas normalizadas (0-1):
 [[0.29411765 0.47058824 0.17647059]
 [0.41176471 0.58823529 0.29411765]
 [0.23529412 0.35294118 0.11764706]
 [0.47058824 0.70588235 0.41176471]
 [0.52941176 0.76470588 0.47058824]]
